sudo: required

services:
  - docker

notifications:
  slack: 
    on_success: never
    on_failure: always
    rooms:
      - oicr:S9k4EowgQv9AnbCfEZHSzCsg

language: java
jdk: 
  - oraclejdk8

before_install:
  - docker build -t quay.io/collaboratory/dockstore-tool-linux-sort .

install: 
  - pip2.7 install --user cwl-runner

script: 
  - cwltool --non-strict Dockstore.cwl test.json 
